service: focusbot

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}

functions:
  main:
    handler: handler.events_create
    events:
      - http:
         path: events/create
         method: post
