service: focusbot
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  main:
    handler: handler.events_create
    events:
      - http:
         path: events/create
         method: post
